apiVersion: apps/v1
kind: Deployment
metadata: 
  name: training
  labels:
    app: training
  namespace: sports-data-center
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name : training-service
        image: zizhuxuexi/training:v1
        ports:
        - containerPort: 10002

---
apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: sports-data-center
spec:
  type: NodePort
  selector:
    app: training
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 10002