mysql:
  driverName: mysql
  host: mysql.sports-data-center.svc.cluster.local
  port: 3306
  database: training
  username: root
  password: 12345678
  charset: utf8mb4

services:
  rowdata:
    name: rowdata.sports-data-center.svc.cluster.local
    namespace: sports-data-center
    port: 10001
